apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: nats-partition
  namespace: cortexops
spec:
  action: partition
  mode: all
  selector:
    labelSelectors:
      app: correlator
  direction: both
  target:
    selector:
      labelSelectors:
        app: nats
    mode: all
  duration: '30s'
  scheduler:
    cron: '@every 2m'
